Add pre-commit hook

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,16 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-b run biome format ./app
+EXTENSION="js|ts|tsx|json|css"
+STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E "(${EXTENSION})$" | tr '\n' ' ')
+
+if [ -z "$STAGED_FILES" ]; then
+  exit 0
+fi
+
+bun biome format $STAGED_FILES --log-level=info
+
+if git diff --cached --quiet; then
+  echo "No changes left to commit. Aborting."
+  exit 1
+fi
